version: 17.03.0.{build}
environment:
  TOKEN:
    secure: TihxnYdIwtxnhS568XO7PECa6ETPBcTk2fUSgO8wq60c75Io9xPXE3TtLCBf5D6h

build_script:
  - ps: choco pack

test_script:
  - ps: .\test.ps1 -cpu x64
  - ps: .\test.ps1 -cpu x86

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG ;
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$') ;
        $version = $version -replace('-ce') ;
        choco apiKey -k $env:TOKEN -source https://chocolatey.org/ ;
        choco push docker.$version.nupkg
      }

artifacts:
  - path: '**\*.nupkg'
    name: Package
